#!/bin/sh
set -eu
OPENFORM_APP_PASSWORD=$(cat /run/secrets/database_app)
OPENFORM_MIGRATE_PASSWORD=$(cat /run/secrets/database_migrate)
export OPENFORM_APP_PASSWORD OPENFORM_MIGRATE_PASSWORD
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set ON_ERROR_STOP=1 <<'SQL'
\getenv app_password OPENFORM_APP_PASSWORD
\getenv migrate_password OPENFORM_MIGRATE_PASSWORD
CREATE ROLE openform_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD :'app_password';
CREATE ROLE openform_migrate LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD :'migrate_password';
ALTER SCHEMA public OWNER TO openform_migrate;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO openform_app;
GRANT CONNECT, CREATE ON DATABASE openform TO openform_migrate;
GRANT CONNECT ON DATABASE openform TO openform_app;
ALTER DEFAULT PRIVILEGES FOR ROLE openform_migrate IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO openform_app;
SQL
unset OPENFORM_APP_PASSWORD OPENFORM_MIGRATE_PASSWORD
