import { useEffect, useRef, useState, type FormEvent } from "react";
import { request } from "./http";
import type { Session, Workspace, Member } from "./identity";
import type { Page } from "./roster";

type Props = { session: Session; workspace: Workspace; onError: (error: unknown) => void };
interface Grant { account_id: string; display_name: string; capabilities: string[]; active: boolean; revision: number; member_eligible: boolean }
const capabilityNames: Record<string, string> = { "activity.read": "查看活动", "activity.edit": "编辑与试做", "activity.publish": "发布版本", "activity.use": "用于开展课堂", "resource.publish": "发布校内资源", "export.create": "导出", "classroom.read": "查看课堂", "classroom.manage": "开停课堂", "records.read": "查看学生记录", "records.delete": "删除资料", "analysis.create": "生成诊断" };

export function CollaborationView({ session, workspace, onError, objectId, kind }: Props & { objectId: string; kind: "activity" | "classroom" }) {
  const base = `/api/workspaces/${workspace.id}`;
  const [grants, setGrants] = useState<Grant[]>([]), [members, setMembers] = useState<Member[]>([]), [cursor, setCursor] = useState<string | null>(null), [grantCursor, setGrantCursor] = useState<string | null>(null);
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const lifetime = useRef<AbortController | null>(null);
  const capabilities = kind === "activity" ? ["activity.read", "activity.edit", "activity.publish", "activity.use", "resource.publish", "export.create"] : ["classroom.read", "classroom.manage", "records.read", "records.delete", "analysis.create", "export.create"];
  useEffect(() => { const controller = new AbortController(); lifetime.current = controller; return () => controller.abort(); }, [objectId]);
  async function act(run: (signal: AbortSignal) => Promise<void>) { const signal = lifetime.current?.signal; if (!signal || signal.aborted) return; setBusy(true); try { await run(signal); } catch (error) { if (!signal.aborted) onError(error); } finally { if (!signal.aborted) setBusy(false); } }
  async function load(signal: AbortSignal) { const [g, m] = await Promise.all([request<Page<Grant>>(`${base}/objects/${objectId}/grants`, { signal }), request<Page<Member>>(`${base}/objects/${objectId}/collaborators`, { signal })]); if (!signal.aborted) { setGrants(g.items); setGrantCursor(g.next_cursor); setMembers(m.items); setCursor(m.next_cursor); setOpen(true); } }
  async function change(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const actor = String(values.get("actor")); const selected = grants.find((grant) => grant.account_id === actor); await act(async (signal) => { await request(`${base}/objects/${objectId}/grants/${actor}`, { method: "PATCH", csrf: session.csrf_token, signal, body: { capabilities: values.getAll("capability"), expected_revision: selected?.revision ?? 0 } }); await load(signal); if (!signal.aborted) setNotice("授权已更新；空权限会撤销原授权。"); }); }
  return workspace.kind !== "campus" ? null : <details className="section"><summary>协作授权 · 仅所属教师可调整</summary><p>逐项授权同校教师；分享教学页面不默认分享课堂回答。编辑、导出和查看记录需要各自授权。</p><button disabled={busy} onClick={() => void act(load)}>读取当前授权</button>{notice && <p role="status">{notice}</p>}{open && <><ul>{grants.map((grant) => <li key={grant.account_id}>{grant.display_name} · {grant.active && grant.member_eligible ? grant.capabilities.map((value) => capabilityNames[value] ?? value).join("、") : "已撤销 / 成员失效"}</li>)}</ul>{grantCursor && <button disabled={busy} onClick={() => void act(async (signal) => { const page = await request<Page<Grant>>(`${base}/objects/${objectId}/grants?cursor=${grantCursor}`, { signal }); if (!signal.aborted) { setGrants((items) => [...items, ...page.items]); setGrantCursor(page.next_cursor); } })}>加载更多授权</button>}
    <form className="compact-form" onSubmit={(event) => void change(event)}><label>协作教师<select name="actor" required defaultValue="" disabled={busy}><option value="" disabled>选择本校教师</option>{members.filter((member) => member.active && member.is_teacher && member.account_id !== session.account_id).map((member) => <option key={member.account_id} value={member.account_id}>{member.display_name}</option>)}</select></label>{cursor && <button type="button" disabled={busy} onClick={() => void act(async (signal) => { const page = await request<Page<Member>>(`${base}/objects/${objectId}/collaborators?cursor=${cursor}`, { signal }); if (!signal.aborted) { setMembers((items) => [...items, ...page.items]); setCursor(page.next_cursor); } })}>加载更多教师</button>}{capabilities.map((value) => <label key={value} className="checkbox-label"><input name="capability" value={value} type="checkbox" disabled={busy} />{capabilityNames[value]}</label>)}<p className="field-help">本次选中项会替换该教师的全部原授权；全部不选即撤销。</p><button disabled={busy}>保存明确授权</button></form></>}</details>;
}

export function ImportedVersions({ session, workspace, onError, activityId, revision }: Props & { activityId: string; revision: number }) {
  const [versions, setVersions] = useState<{ number: number; title: string }[]>([]), [busy, setBusy] = useState(false);
  const lifetime = useRef<AbortController | null>(null);
  const base = `/api/workspaces/${workspace.id}/activities/${activityId}/imported-versions`;
  useEffect(() => { const controller = new AbortController(); lifetime.current = controller; void request<{ items: { number: number; title: string }[] }>(base, { signal: controller.signal }).then((value) => { if (!controller.signal.aborted) setVersions(value.items); }).catch((error) => { if (!controller.signal.aborted) onError(error); }); return () => controller.abort(); }, [base]);
  async function restore(number: number) { const signal = lifetime.current?.signal; if (!signal || signal.aborted) return; setBusy(true); try { await request(`${base}/${number}/restore`, { method: "POST", csrf: session.csrf_token, signal, body: { expected_revision: revision } }); if (!signal.aborted) location.hash = `#T03?activity=${activityId}`; } catch (error) { if (!signal.aborted) onError(error); } finally { if (!signal.aborted) setBusy(false); } }
  return !versions.length ? null : <details><summary>导入来源版本材料</summary><p>切换会替换当前草稿；固定发布版本保留，新的草稿仍须重新试做。</p>{versions.map((version) => <div className="list-row" key={version.number}><span>v{version.number} · {version.title}</span><button disabled={busy} onClick={() => void restore(version.number)}>使用此材料制作</button></div>)}</details>;
}
