import { can, select, readable, statistics, lessonContent } from './model.mjs';
import { esc as e, time, url, route, link, button, badge, notice, empty, heading, field, textarea, selectField, check, table, row, tabs, statsHTML, questionStats, typeNames, statusNames } from './ui.mjs';

export function teacherPage(ctx) {
  const { state:s, actor, r, space } = ctx;
  const data = select(s,actor,space);
  const p = (extra={}) => ({space,mode:r.mode,...extra});
  const {page,...params}=r;
  const here=url(page,p(params));
  const search = (placeholder) => `<form data-form="filter" class="toolbar"><label class="search"><span class="subtle">${placeholder}</span><input name="q" value="${e(r.q || '')}" placeholder="${placeholder}" aria-label="${placeholder}"></label><button>搜索</button>${r.q?link('清除',r.page,p()):''}</form>`;
  const filter = list => list.filter(item=>JSON.stringify([item.title,item.draft?.title,item.name]).toLowerCase().includes((r.q||'').toLowerCase()));
  const className = id => s.classes[id]?.name || '快速活动';
  const activityLink = activity => link(activity.draft.title,'T02',p({activity:activity.id,back:url('T01',p({q:r.q}))}),'list-title');
  const lessonLink = lesson => link(lesson.title,'T06',p({lesson:lesson.id,back:here}),'list-title');
  const classLink = cls => link(cls.name,'T09',p({class:cls.id,mode:r.mode,back:url(r.page,p({q:r.q}))}),'list-title');
  switch (r.page) {
    case 'T01': return heading('我的活动','把教学想法变成学生可以参与的活动。',button('新建活动','new-activity',{},'primary')) + (data.lessons.some(l=>l.status==='open') ? notice(`${link('继续接收中的课堂','T06',p({lesson:data.lessons.find(l=>l.status==='open').id}))} · 学生进度和最终提交分开统计。`,'good') : '') + search('搜索活动名称') + table(['活动名称','活动类型','草稿 / 版本','来源','操作'],filter(data.activities).map(a=>row([activityLink(a),e(typeNames[a.draft.type]),`${badge(`修订 ${a.revision}`,a.verifiedRevision===a.revision?'green':'amber')}<small>${a.versions.length} 个固定版本</small>`,e(a.source),link('继续制作','T03',p({activity:a.id,back:here}))])));
    case 'T02': {
      const a = readable(s,actor,'activities',r.activity);
      const version = a.versions.find(v=>v.id===r.version) || a.versions.at(-1);
      if(r.version&&!a.versions.some(v=>v.id===r.version)) throw new Error('所选活动版本不存在，请返回活动详情重新选择。');
      const fixed = Boolean(r.version);
      const content = fixed ? version : a.draft;
      const versionParams = {activity:a.id,version:r.version,back:r.back};
      const details = heading(content.title, fixed ? `固定版本 ${e(version.label)} · 修订 ${version.revision} · 只读内容` : `${e(typeNames[a.draft.type])} · 当前草稿`,
        link(fixed?'编辑当前草稿':'继续制作','T03',p({activity:a.id,back:here}),'btn') + (version?button('开展活动','launch',{activity:a.id,version:version.id},'primary'):''));
      const tabbar = tabs([['versions','内容与版本',url('T02',p(versionParams))],['lessons','历次课堂',url('T02',p({...versionParams,tab:'lessons'}))]],r.tab||'versions');
      if(r.tab==='lessons') return details + tabbar + table(['课堂','参与方式','状态','完成人数'],data.lessons.filter(l=>l.activity===a.id&&(!fixed||l.version===version.id)).map(l=>row([lessonLink(l),e(className(l.classId)),badge(statusNames[l.status]),String(statistics(s,l.id).completed)])));
      return details + tabbar + `<div class="two-col"><section class="panel"><h2>${fixed?'本版本教学内容':'当前草稿内容'}</h2><p>${e(content.goal)}</p>${content.questions.map((q,i)=>`<div class="list-row"><div><small>第 ${i+1} 题</small><h3>${e(q.title)}</h3><p class="muted">${q.options?.map(e).join(' / ') || '学生填写回答'}</p></div></div>`).join('')}</section><section class="stack"><div class="panel"><h2>${fixed?'固定版本 '+e(version.label):'草稿修订 '+a.revision}</h2>${fixed?badge('已固定 · 只读','green'):badge(a.verifiedRevision===a.revision?'本修订已验证':'需要试做',a.verifiedRevision===a.revision?'green':'amber')}<p class="muted">${fixed?'这里展示本课堂实际使用的内容。编辑当前草稿不会改变此版本。':'修改草稿不会影响已开展课堂的固定版本。'}</p></div><div class="panel"><h2>固定版本</h2>${a.versions.length ? a.versions.map(v=>`<div class="list-row"><div>${link(v.label,'T02',p({activity:a.id,version:v.id,back:r.back}),'list-title')}<small class="block">修订 ${v.revision} · ${time(v.createdAt)}</small></div>${button('开展','launch',{activity:a.id,version:v.id})}${space==='school'?button('发布资源','publish-resource',{activity:a.id,version:v.id}):''}</div>`).join('') : '<p class="muted">完成试做后生成第一个固定版本。</p>'}</div></section></div>`;
    }
    case 'T03': {
      const a = readable(s,actor,'activities',r.activity);
      const trials = Object.values(s.trials).filter(t=>t.activity===a.id && t.revision===a.revision);
      const done = trials.find(t=>t.saved&&t.receipt);
      const tab = r.tab || 'make';
      const top = heading(a.draft.title,`草稿修订 ${a.revision} · ${a.verifiedRevision===a.revision?'已验证，可开展':'修改后需要重新试做'}`,a.verifiedRevision===a.revision?button('开展活动','launch',{activity:a.id,version:a.versions.find(v=>v.revision===a.revision)?.id},'primary'):'') + tabs([['make','制作活动',url('T03',p({activity:a.id,back:r.back}))],['trial','试做与接入检查',url('T03',p({activity:a.id,tab:'trial',back:r.back}))]],tab);
      if (tab==='trial') return top + `<div class="two-col"><section class="panel"><h2>用学生视角完整做一次</h2><p>试做独立保存，绑定当前修订，不会进入课堂统计或学生历史。</p><ul class="checklist"><li>接收一次进度保存 ${badge(done?.saved?'已收到':'待检查',done?.saved?'green':'amber')}</li><li>接收一次完整提交 ${badge(done?.receipt?'已收到试做回执':'待检查',done?.receipt?'green':'amber')}</li><li>教师复核内容 ${badge(a.verifiedRevision===a.revision?'已确认':'待确认')}</li></ul><div class="action-row">${button('开始学生视角试做','start-trial',{activity:a.id},'primary')}</div>${trials.map(t=>`<div class="list-row"><div>修订 ${t.revision} · ${t.receipt?'已完成':'进行中'}<small class="block">${time(t.savedAt)}</small></div>${link(t.receipt?'查看试做':'继续试做','S02',p({trial:t.id,back:r.back}),'btn')}</div>`).join('')}</section><section class="panel"><h2>确认发布版本</h2><form data-form="verify">${check('已检查题目、答案与内容适合本班学生','confirmed',a.verifiedRevision===a.revision)}<p class="muted">此处固定活动内容；开展课堂时选择参与班级和接收状态。</p><button class="primary" ${done?'':'disabled'}>确认检查并固定版本</button></form></section></div>`;
      return top + `<form data-form="editor" data-revision="${a.revision}" class="editor"><section class="panel"><h2>教学设计</h2>${field('活动名称','title',a.draft.title,'text','required maxlength="80"')}${textarea('教学目标','goal',a.draft.goal,'maxlength="2000"')}<p class="field-help">${e(typeNames[a.draft.type])} · 三道结构化题目。此原型不调用生成模型。</p><button class="primary">保存修改</button><span class="save-state" id="save-state">已保存修订 ${a.revision}</span>${a.html?button('隔离预览导入 HTML','html-preview',{activity:a.id}):''}</section><section class="preview-frame"><div class="preview-chrome">编辑学生将看到的题目 · 修改后需要重新试做</div><div class="preview-content">${a.draft.questions.map((q,i)=>`${textarea(`第 ${i+1} 题`,'question-'+q.id,q.title,'required maxlength="300"')}${q.options?`<div class="options">${q.options.map(o=>`<div class="option btn" aria-disabled="true">${e(o)}${o===q.correct?' · 标准答案':''}</div>`).join('')}</div>`:notice('学生在这里填写文字或数字。','')}<hr>`).join('')}</div></section></form>`;
    }
    case 'T05': return heading('我的课堂','每次开展都是独立课堂，保留使用的固定版本。',link('选择活动开展','T01',p(),'btn primary')) + search('搜索课堂名称') + table(['课堂名称','班级 / 方式','接收状态','完成 / 参与','开展时间','操作'],filter(data.lessons).slice().reverse().map(l=>{const st=statistics(s,l.id);return row([lessonLink(l),e(className(l.classId)),badge(statusNames[l.status],l.status==='open'?'green':''),`${st.completed} / ${st.participants}`,time(l.createdAt),button('再次开展','launch',{activity:l.activity,version:l.version,class:l.classId||''})]);}));
    case 'T06': {
      const l = readable(s,actor,'lessons',r.lesson); const v = lessonContent(s,l.id); const st = statistics(s,l.id); const tab = r.tab||'overview';
      const tabbar = tabs([['overview','课堂概况'],['records','参与记录'],['reports','教学诊断'],['sharing','反馈与共享']].map(([key,label])=>[key,label,url('T06',p({lesson:l.id,tab:key,back:r.back}))]),tab);
      const top = heading(l.title,`${e(className(l.classId))} · ${e(v.label)} · ${badge(statusNames[l.status],l.status==='open'?'green':'amber')}`,button('学生参与入口','entry',{lesson:l.id},'primary') + (l.status!=='ended'?button(l.status==='open'?'暂停接收':'恢复接收','lesson-status',{lesson:l.id,status:l.status==='open'?'paused':'open'})+button('结束课堂','end-lesson',{lesson:l.id},'danger'):button('再次开展','launch',{activity:l.activity,version:l.version,class:l.classId||''}))) + tabbar;
      if (tab==='records') return top + statsHTML(st) + table(['学生 / 稳定标识','尝试','状态','最近确认','操作'],Object.values(s.attempts).filter(a=>a.lesson===l.id).map(a=>row([`${e(s.students[a.student]?.name||'学生')}<small>${e(a.student)}</small>`,String(a.number),badge(a.receipt?'已提交':'进行中',a.receipt?'green':'amber'),time(a.savedAt),button('查看作答','evidence',{attempt:a.id}) + button('删除','delete-attempt',{attempt:a.id},'link danger')]))) + `<div class="row" style="margin-top:16px">${button('导出课堂记录','export',{lesson:l.id})}<small>同一学生多次尝试保留历史，完成率按最近有效完成计算。</small></div>`;
      if (tab==='reports') return top + notice('诊断为固定范围的示例归纳。新增提交不会改写已有报告，教师需要复核。','') + `<div class="row" style="margin-bottom:16px">${button('生成新的诊断示例','report',{lesson:l.id},'primary')}</div>` + table(['报告','截止时间','覆盖','复核状态'],Object.values(s.reports).filter(rep=>rep.lesson===l.id).reverse().map(rep=>row([link(`教学诊断 #${rep.number}`,'T07',p({lesson:l.id,report:rep.id,back:here})),time(rep.createdAt),`${rep.stats.completed} 人，${rep.stats.submittedAttempts} 次提交`,badge(rep.invalid?'依据已删除':rep.reviewed?'教师已复核':'待教师复核',rep.reviewed?'green':'amber')])));
      if (tab==='sharing') return top + `<div class="two-col"><section class="panel"><h2>本人反馈</h2><form data-form="feedback">${check('学生可查看本人答案与教师反馈','open',l.feedback)}${textarea('给本课堂学生的反馈','text',l.feedbackText||'')}<button class="primary">保存反馈设置</button></form><p class="field-help">未开放反馈时，学生仍可查看自己的提交回执。</p></section><section class="panel"><h2>共享结果</h2>${badge(l.sharing?`已开放 · 发布 ${l.sharing.number}`:'尚未开放',l.sharing?'green':'')}<p>默认仅共享题目汇总，不含学生姓名、个人码和原始答卷。规则汇总不依赖 AI 诊断。</p><div class="row">${button(l.sharing?'预览并更新':'预览共享内容','preview-share',{lesson:l.id},'primary')}${l.sharing?button('撤回共享','revoke-share',{lesson:l.id},'danger'):''}</div>${l.sharing?`<p class="field-help">发布于 ${time(l.sharing.createdAt)}，覆盖 ${l.sharing.stats.completed} 人；之后收到的数据需重新预览发布。</p>`:''}</section></div>`;
      return top + (l.status==='paused'?notice('接收已暂停。已确认记录仍可查看，恢复后学生可继续保存与提交。','warn'):'') + `<section class="panel"><h2>参与概况</h2>${statsHTML(st)}<p class="data-time">按本浏览器已确认的演示记录计算 · 跨标签页自动更新</p></section><div class="two-col" style="margin-top:20px"><section class="panel"><h2>题目汇总</h2>${questionStats(st)}</section><section class="panel"><h2>课堂安排</h2><dl class="detail-grid"><dt>参与方式</dt><dd>${l.kind==='class'?'班级个人码':'快速临时参与'}</dd><dt>课堂码</dt><dd class="mono">${e(l.code)}</dd><dt>使用活动</dt><dd>${link(v.title,'T02',p({activity:l.activity,version:l.version,back:here}))}</dd><dt>固定版本</dt><dd>${e(v.label)}</dd><dt>开展时间</dt><dd>${time(l.createdAt)}</dd></dl><p class="source-note">课堂码只定位课堂；班级个人码验证学生身份。</p>${link('查看参与记录','T06',p({lesson:l.id,tab:'records',back:r.back}),'btn')}</section></div>`;
    }
    case 'T07': {
      const rep = readable(s,actor,'reports',r.report); if (r.lesson && rep.lesson!==r.lesson) throw new Error('报告与当前课堂不匹配。');
      const l = readable(s,actor,'lessons',rep.lesson);
      const parent=r.back?route(r.back):{};
      const classroomBack=parent.page==='T06'&&parent.lesson===l.id?parent.back:undefined;
      if (rep.invalid) return heading('报告依据已失效') + notice('相关原始记录已删除，请根据当前有效记录生成新报告。','warn') + link('返回课堂诊断','T06',p({lesson:l.id,tab:'reports',back:classroomBack}),'btn primary');
      return heading(`${l.title} · 诊断 #${rep.number}`,`固定范围截至 ${time(rep.createdAt)}`,button('教师复核完成','review-report',{report:rep.id},'primary') + link('返回课堂诊断','T06',p({lesson:l.id,tab:'reports',back:classroomBack}),'btn')) + notice('本页是可追溯的诊断呈现示例，未调用 AI 模型。图片不参与分析，不能作为自动评分结论。','warn') + `<section class="panel report-copy">${badge(rep.reviewed?'教师已复核':'待教师复核',rep.reviewed?'green':'amber')}${statsHTML(rep.stats)}<h2>1. 完成与覆盖范围</h2><p>本次覆盖 ${rep.stats.completed} 名已完成参与者。进行中内容不纳入归纳；没有有效答案的题目不补零、不推算正确率。</p><h2>2. 题目表现</h2>${questionStats(rep.stats)}<h2>3. 教学建议示例</h2><p>先共同回顾答错较多的题目，再让学生解释思考过程。开放题需要教师逐条复核，以下依据可返回原始提交。</p><div class="row">${rep.stats.attemptIds.map(id=>button(`查看 ${s.students[s.attempts[id]?.student]?.name||'学生'} 的依据`,'evidence',{attempt:id})).join('')}</div></section>`;
    }
    case 'T08': return heading('我的班级','只显示获授任课的班级；班级管理与课堂作答权限分别判断。',space==='personal'?button('新建班级','new-class',{},'primary'):'') + table(['班级名称','学生人数','任课教师','操作'],data.classes.filter(c=>c.teachers.includes(actor.id)).map(c=>row([classLink(c),String(Object.values(s.students).filter(st=>st.classId===c.id).length),c.teachers.map(t=>e(s.members[t]?.name)).join('、'),button('开展活动','launch',{class:c.id})])));
    case 'T09': {
      const cls = readable(s,actor,'classes',r.class); const adminMode=r.mode==='admin'; const teaching=can(s,actor,space)&&cls.teachers.includes(actor.id)&&!adminMode;
      return heading(cls.name,`${e(s.spaces[space].name)} · ${adminMode?'管理视图':'教学视图'}`,teaching?button('为本班开展活动','launch',{class:cls.id},'primary'):link('维护学生名册','C03',p({class:cls.id,mode:'admin'}),'btn primary')) + (adminMode?notice('此视图展示班级、名单与任课，不授予课堂答卷查看权限。',''):'') + `<section class="panel" style="margin-bottom:20px"><h2>班级信息</h2><p>任课教师：${cls.teachers.map(t=>e(s.members[t]?.name)).join('、')||'待指定'}</p><p>同名学生由稳定学生标识区分。个人码重置不会删除已确认历史。</p></section>` + table(['姓名','稳定学生标识','个人码','操作'],Object.values(s.students).filter(st=>st.classId===cls.id).map(st=>row([e(st.name),`<span class="mono">${e(st.id)}</span>`,`<span class="token">${e(st.code||'待重新发放')}</span>`,button('重置个人码','reset-code',{student:st.id})]))) + (teaching?`<section class="panel" style="margin-top:20px"><h2>我的班级课堂</h2>${data.lessons.filter(l=>l.classId===cls.id).map(l=>`<div class="list-row">${lessonLink(l)}${badge(statusNames[l.status])}</div>`).join('')||'<p class="muted">尚未为本班开展课堂。</p>'}</section>`:'');
    }
    case 'T10': return heading(r.mode==='admin'?'校内资源管理':'校内资源库','复用教学内容；不复制班级名单、学生记录或凭据。') + search('搜索资源名称') + table(['资源','活动类型','发布教师','状态','操作'],filter(data.resources).map(res=>row([link(res.title,'T11',p({resource:res.id,mode:r.mode,back:url('T10',p({mode:r.mode,q:r.q}))})),e(typeNames[res.content.type]),e(s.members[res.owner]?.name),badge(res.active?'可复用':'已撤回',res.active?'green':''),res.active&&can(s,actor,space)?button('复制到我的活动','copy-resource',{resource:res.id}):'—'])));
    case 'T11': {
      const res=readable(s,actor,'resources',r.resource);
      return heading(res.title,`发布教师 ${e(s.members[res.owner]?.name)} · ${e(res.content.label)} · ${time(res.createdAt)}`,res.active&&can(s,actor,space)?button('复制到我的活动','copy-resource',{resource:res.id},'primary'):'') + (!res.active?notice('此资源已撤回，不能再创建新副本。此前复制的活动独立保留。','warn'):'') + `<div class="two-col"><section class="panel"><h2>资源内容</h2><p>${e(res.content.goal)}</p>${res.content.questions.map(q=>`<div class="list-row"><div><h3>${e(q.title)}</h3><p class="muted">${q.options?.map(e).join(' / ')||'开放回答'}</p></div></div>`).join('')}</section><section class="panel"><h2>使用说明</h2><p>副本保存到当前学校的“我的活动”，修改与重新试做后开展。</p><p>来源更新或撤回不改变已产生的独立副本。</p>${res.active&&(res.owner===actor.id||can(s,actor,space,'admin'))?button('撤回资源','revoke-resource',{resource:res.id},'danger'):''}</section></div>`;
    }
    case 'T12': {
      const tab = r.tab||'tasks';
      let body = table(['任务名称','时间','状态','结果'],data.tasks.slice().reverse().map(task=>row([e(task.title),time(task.createdAt),badge(task.status==='invalid'?'源记录已删除':'已完成',task.status==='invalid'?'amber':'green'),task.status==='invalid'?'请重新导出':task.package?button('下载资料包','download',{task:task.id}):task.target?.type==='activity'?link('打开导入活动','T03',p({activity:task.target.id})):link('查看只读档案','T12',p({tab:'archives',archive:task.target?.id}))])));
      if (tab==='archives') body=table(['档案名称','导入时间','记录数','操作'],data.archives.map(archive=>row([e(archive.title),time(archive.createdAt),String(archive.records.length),link('查看档案','T12',p({tab:'archives',archive:archive.id}))])));
      if (r.archive) { const archive=readable(s,actor,'archives',r.archive); body+=`<section class="panel" style="margin-top:20px"><h2>${e(archive.title)}</h2>${notice('只读历史档案，不建立当前学生身份，也不计入课堂统计和本人记录。','')}<pre class="readonly-content">${e(JSON.stringify(archive.records,null,2))}</pre></section>`; }
      return heading('资料迁移与档案','任务离开后仍可找回。资源导入为新草稿，数据导入为只读档案。',button('导入资料包','import-package',{},'primary') + button('下载资源样例','sample-package')) + tabs([['tasks','迁移任务',url('T12',p())],['archives','只读档案',url('T12',p({tab:'archives'}))]],tab) + body;
    }
    default: throw new Error('未找到这个教学页面。');
  }
}
